import { Toaster } from "@/__shared__/components/ui/toaster";
import { Inter } from "next/font/google";
import React from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <div className="relative flex min-h-screen flex-col">
          <header className={"flex h-16 items-center bg-gray-50"}>
            header
          </header>
          <main className="flex-1 space-y-8 bg-[#e6f2ff] p-24">{children}</main>
          <footer className={"flex h-16 items-center"}>footer</footer>
        </div>

        <Toaster />
      </body>
    </html>
  );
}
